// <auto-generated />
using System;
using GameData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameData.Migrations
{
    [DbContext(typeof(DbForGame))]
    [Migration("20250527081319_primarydata")]
    partial class primarydata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameForClients.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Player1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Player2Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Player1Id = 1,
                            Player2Id = 2,
                            StartedAt = new DateTime(2025, 5, 26, 8, 13, 19, 474, DateTimeKind.Utc).AddTicks(6018)
                        });
                });

            modelBuilder.Entity("GameForClients.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "User logged in",
                            CreatedAt = new DateTime(2025, 5, 26, 7, 13, 19, 474, DateTimeKind.Utc).AddTicks(6149),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Action = "User started game",
                            CreatedAt = new DateTime(2025, 5, 26, 7, 43, 19, 474, DateTimeKind.Utc).AddTicks(6151),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("GameForClients.Models.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHit")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MoveTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Moves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            IsHit = false,
                            MoveTime = new DateTime(2025, 5, 26, 9, 13, 19, 474, DateTimeKind.Utc).AddTicks(6065),
                            PlayerId = 1,
                            X = 0,
                            Y = 0
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            IsHit = true,
                            MoveTime = new DateTime(2025, 5, 26, 10, 13, 19, 474, DateTimeKind.Utc).AddTicks(6068),
                            PlayerId = 2,
                            X = 1,
                            Y = 0
                        });
                });

            modelBuilder.Entity("GameForClients.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cells")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("ShipType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Ships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cells = "0,0;0,1;0,2",
                            GameId = 1,
                            PlayerId = 1,
                            ShipType = "Destroyer"
                        },
                        new
                        {
                            Id = 2,
                            Cells = "1,0;1,1;1,2",
                            GameId = 1,
                            PlayerId = 2,
                            ShipType = "Submarine"
                        });
                });

            modelBuilder.Entity("GameForClients.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 27, 8, 13, 19, 472, DateTimeKind.Utc).AddTicks(6104),
                            PasswordHash = "AQAAAAEAACcQAAAAEBNzTgHxS05ue64XsPlofTKVrSrD9HDek1m1KC3mx7FkuRHcH0wKiJ17WmyLvQ+tRQ==",
                            Username = "player1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 27, 8, 13, 19, 473, DateTimeKind.Utc).AddTicks(6052),
                            PasswordHash = "AQAAAAEAACcQAAAAEKUDNokCmt34D3lmA50FdUB6/NdjcqcbjEHMlQr2pMEyeK5xg4mflO0VZjoIbfPy5w==",
                            Username = "player2"
                        });
                });

            modelBuilder.Entity("GameForClients.Models.Game", b =>
                {
                    b.HasOne("GameForClients.Models.User", "Player1")
                        .WithMany("GamesAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameForClients.Models.User", "Player2")
                        .WithMany("GamesAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GameForClients.Models.User", "Winner")
                        .WithMany("GamesWon")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("GameForClients.Models.Log", b =>
                {
                    b.HasOne("GameForClients.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameForClients.Models.Move", b =>
                {
                    b.HasOne("GameForClients.Models.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameForClients.Models.User", "Player")
                        .WithMany("Moves")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameForClients.Models.Ship", b =>
                {
                    b.HasOne("GameForClients.Models.Game", "Game")
                        .WithMany("Ships")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameForClients.Models.User", "Player")
                        .WithMany("Ships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameForClients.Models.Game", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("Ships");
                });

            modelBuilder.Entity("GameForClients.Models.User", b =>
                {
                    b.Navigation("GamesAsPlayer1");

                    b.Navigation("GamesAsPlayer2");

                    b.Navigation("GamesWon");

                    b.Navigation("Logs");

                    b.Navigation("Moves");

                    b.Navigation("Ships");
                });
#pragma warning restore 612, 618
        }
    }
}
